// Datos de ejemplo para modo demo (sin conexión a Supabase)

import type { ProyectoConEstadisticas } from '@/lib/hooks/useProyectos';

export const MOCK_PROYECTOS: ProyectoConEstadisticas[] = [
  {
    id: '1',
    nombre_cliente: 'ZonaT',
    nombre_proyecto: 'Sistema POS ZonaT',
    api_key_unica: 'zt_demo_key_123',
    url_dominio: 'https://zonat.programamos.co',
    status_servidor: 'active',
    descripcion: 'Sistema de punto de venta para tiendas ZonaT en Sincelejo',
    logo_url: null,
    color_marca: '#FF6B6B',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // hace 2 min
    actividad_ultima_hora: 47,
    errores_ultima_hora: 0,
    usuarios_activos: 5,
    ultimo_error: null,
    top_modulos: [
      { modulo: 'Ventas', total_usos: 23 },
      { modulo: 'Inventario', total_usos: 15 },
      { modulo: 'Reportes', total_usos: 9 }
    ],
    status_visual: 'active'
  },
  {
    id: '2',
    nombre_cliente: 'Aleya',
    nombre_proyecto: 'ERP Aleya',
    api_key_unica: 'al_demo_key_456',
    url_dominio: 'https://aleya.programamos.co',
    status_servidor: 'active',
    descripcion: 'Sistema ERP completo para gestión empresarial',
    logo_url: null,
    color_marca: '#4ECDC4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(), // hace 1 min
    actividad_ultima_hora: 89,
    errores_ultima_hora: 2,
    usuarios_activos: 12,
    ultimo_error: {
      id: 'err1',
      proyecto_id: '2',
      usuario_id: null,
      usuario_nombre: 'María García',
      usuario_email: 'maria@aleya.com',
      modulo_visitado: 'Facturación',
      accion_realizada: 'Generar factura electrónica',
      metadata: null,
      es_error: true,
      error_mensaje: 'Error de conexión con DIAN',
      error_stack: null,
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0',
      duracion_ms: null,
      timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString()
    },
    top_modulos: [
      { modulo: 'Facturación', total_usos: 34 },
      { modulo: 'Contabilidad', total_usos: 28 },
      { modulo: 'Nómina', total_usos: 17 }
    ],
    status_visual: 'active'
  },
  {
    id: '3',
    nombre_cliente: 'TechStore',
    nombre_proyecto: 'E-commerce TechStore',
    api_key_unica: 'ts_demo_key_789',
    url_dominio: 'https://techstore.programamos.co',
    status_servidor: 'error',
    descripcion: 'Tienda online de productos tecnológicos',
    logo_url: null,
    color_marca: '#8c52ff',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 30 * 1000).toISOString(), // hace 30 seg
    actividad_ultima_hora: 156,
    errores_ultima_hora: 5,
    usuarios_activos: 23,
    ultimo_error: {
      id: 'err2',
      proyecto_id: '3',
      usuario_id: null,
      usuario_nombre: 'Carlos Mendez',
      usuario_email: 'carlos@techstore.com',
      modulo_visitado: 'Checkout',
      accion_realizada: 'Procesar pago',
      metadata: null,
      es_error: true,
      error_mensaje: 'Payment gateway timeout - Wompi no responde',
      error_stack: null,
      ip_address: '201.184.50.25',
      user_agent: 'Mozilla/5.0',
      duracion_ms: null,
      timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString()
    },
    top_modulos: [
      { modulo: 'Catálogo', total_usos: 67 },
      { modulo: 'Carrito', total_usos: 45 },
      { modulo: 'Checkout', total_usos: 34 }
    ],
    status_visual: 'error'
  },
  {
    id: '4',
    nombre_cliente: 'Farmacia Central',
    nombre_proyecto: 'Sistema Farmacia',
    api_key_unica: 'fc_demo_key_321',
    url_dominio: 'https://farmacia.programamos.co',
    status_servidor: 'inactive',
    descripcion: 'Sistema de gestión para farmacias',
    logo_url: null,
    color_marca: '#22c55e',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // hace 45 min
    actividad_ultima_hora: 8,
    errores_ultima_hora: 0,
    usuarios_activos: 0,
    ultimo_error: null,
    top_modulos: [
      { modulo: 'Dispensación', total_usos: 5 },
      { modulo: 'Inventario', total_usos: 3 }
    ],
    status_visual: 'inactive'
  },
  {
    id: '5',
    nombre_cliente: 'Restaurante El Sabor',
    nombre_proyecto: 'POS Restaurante',
    api_key_unica: 'rs_demo_key_654',
    url_dominio: 'https://elsabor.programamos.co',
    status_servidor: 'active',
    descripcion: 'Sistema de punto de venta para restaurantes',
    logo_url: null,
    color_marca: '#f59e0b',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    actividad_ultima_hora: 234,
    errores_ultima_hora: 0,
    usuarios_activos: 8,
    ultimo_error: null,
    top_modulos: [
      { modulo: 'Pedidos', total_usos: 112 },
      { modulo: 'Cocina', total_usos: 89 },
      { modulo: 'Caja', total_usos: 33 }
    ],
    status_visual: 'active'
  },
  {
    id: '6',
    nombre_cliente: 'Gimnasio FitLife',
    nombre_proyecto: 'GymManager',
    api_key_unica: 'gf_demo_key_987',
    url_dominio: 'https://fitlife.programamos.co',
    status_servidor: 'active',
    descripcion: 'Sistema de gestión para gimnasios',
    logo_url: null,
    color_marca: '#ec4899',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_activity_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    actividad_ultima_hora: 45,
    errores_ultima_hora: 0,
    usuarios_activos: 3,
    ultimo_error: null,
    top_modulos: [
      { modulo: 'Check-in', total_usos: 28 },
      { modulo: 'Membresías', total_usos: 12 },
      { modulo: 'Clases', total_usos: 5 }
    ],
    status_visual: 'active'
  }
];

export const MOCK_ACTIVIDADES = [
  {
    id: '1',
    proyecto_id: '3',
    usuario_id: null,
    usuario_nombre: 'Carlos Mendez',
    usuario_email: 'carlos@techstore.com',
    modulo_visitado: 'Checkout',
    accion_realizada: 'Procesar pago',
    metadata: null,
    es_error: true,
    error_mensaje: 'Payment gateway timeout - Wompi no responde',
    error_stack: null,
    ip_address: '201.184.50.25',
    user_agent: 'Mozilla/5.0',
    duracion_ms: null,
    timestamp: new Date(Date.now() - 30 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'E-commerce TechStore', color_marca: '#8c52ff' }
  },
  {
    id: '2',
    proyecto_id: '5',
    usuario_id: null,
    usuario_nombre: 'Ana López',
    usuario_email: 'ana@elsabor.com',
    modulo_visitado: 'Pedidos',
    accion_realizada: 'Crear nuevo pedido - Mesa 5',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '192.168.1.50',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 234,
    timestamp: new Date(Date.now() - 45 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'POS Restaurante', color_marca: '#f59e0b' }
  },
  {
    id: '3',
    proyecto_id: '1',
    usuario_id: null,
    usuario_nombre: 'Pedro Martínez',
    usuario_email: 'pedro@zonat.com',
    modulo_visitado: 'Ventas',
    accion_realizada: 'Factura #4523 generada',
    metadata: { total: 125000 },
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '190.25.100.50',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 156,
    timestamp: new Date(Date.now() - 60 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'Sistema POS ZonaT', color_marca: '#FF6B6B' }
  },
  {
    id: '4',
    proyecto_id: '2',
    usuario_id: null,
    usuario_nombre: 'María García',
    usuario_email: 'maria@aleya.com',
    modulo_visitado: 'Contabilidad',
    accion_realizada: 'Conciliación bancaria completada',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 2340,
    timestamp: new Date(Date.now() - 90 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'ERP Aleya', color_marca: '#4ECDC4' }
  },
  {
    id: '5',
    proyecto_id: '6',
    usuario_id: null,
    usuario_nombre: 'Laura Sánchez',
    usuario_email: 'laura@fitlife.com',
    modulo_visitado: 'Check-in',
    accion_realizada: 'Check-in miembro #1234',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '192.168.2.10',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 89,
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'GymManager', color_marca: '#ec4899' }
  },
  {
    id: '6',
    proyecto_id: '5',
    usuario_id: null,
    usuario_nombre: 'José Rodríguez',
    usuario_email: 'jose@elsabor.com',
    modulo_visitado: 'Cocina',
    accion_realizada: 'Pedido #892 listo para servir',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '192.168.1.51',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 45,
    timestamp: new Date(Date.now() - 2.5 * 60 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'POS Restaurante', color_marca: '#f59e0b' }
  },
  {
    id: '7',
    proyecto_id: '3',
    usuario_id: null,
    usuario_nombre: 'Diego Torres',
    usuario_email: 'diego@techstore.com',
    modulo_visitado: 'Catálogo',
    accion_realizada: 'Actualizar precio producto SKU-8834',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '201.184.50.30',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 123,
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'E-commerce TechStore', color_marca: '#8c52ff' }
  },
  {
    id: '8',
    proyecto_id: '1',
    usuario_id: null,
    usuario_nombre: 'Sandra Jiménez',
    usuario_email: 'sandra@zonat.com',
    modulo_visitado: 'Inventario',
    accion_realizada: 'Entrada de mercancía - 50 unidades',
    metadata: null,
    es_error: false,
    error_mensaje: null,
    error_stack: null,
    ip_address: '190.25.100.51',
    user_agent: 'Mozilla/5.0',
    duracion_ms: 567,
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    proyectos_maestros: { nombre_proyecto: 'Sistema POS ZonaT', color_marca: '#FF6B6B' }
  }
];
